# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renamebox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rename_file(object):
    def setupUi(self, rename_file):
        rename_file.setObjectName("rename_file")
        rename_file.resize(281, 118)
        self.cancel_button_rename_box = QtWidgets.QDialogButtonBox(rename_file)
        self.cancel_button_rename_box.setGeometry(QtCore.QRect(100, 80, 171, 32))
        self.cancel_button_rename_box.setOrientation(QtCore.Qt.Horizontal)
        self.cancel_button_rename_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.cancel_button_rename_box.setObjectName("cancel_button_rename_box")
        self.label = QtWidgets.QLabel(rename_file)
        self.label.setGeometry(QtCore.QRect(10, 0, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(rename_file)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 261, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(rename_file)
        self.cancel_button_rename_box.accepted.connect(rename_file.accept)
        self.cancel_button_rename_box.rejected.connect(rename_file.reject)
        QtCore.QMetaObject.connectSlotsByName(rename_file)

    def retranslateUi(self, rename_file):
        _translate = QtCore.QCoreApplication.translate
        rename_file.setWindowTitle(_translate("rename_file", "Rename File"))
        self.label.setText(_translate("rename_file", "New File Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rename_file = QtWidgets.QDialog()
    ui = Ui_rename_file()
    ui.setupUi(rename_file)
    rename_file.show()
    sys.exit(app.exec_())
